import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "calculadora",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head><link rel="icon" href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-EYqWWoOa71wdGlnNizlBpijvPEouHH9DVoElDvz6OIvZmHpumtxl2ojF8-nZzYY0uiA&usqp=CAU" sizes="any" /></head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
